#cloud-config
users:
  - default
  - name: node_exporter
    homedir: /bin/false

write_files:
  # Add Node Export Service file
  - path: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter --collector.processes --collector.systemd

      [Install]
      WantedBy=multi-user.target
  # Wget Configuration
  - path: /etc/wgetrc
    append: true
    content: |
      #http_proxy = Add Proxy Here
      #https_proxy = Add Proxy Here
      #use_proxy = on

runcmd:
  - echo ">>> Creating Directory"
  - sudo mkdir -p /run/install/node_exporter
  - echo ">>> Getting Node Exporter"
  - sudo wget https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz -O /run/install/node_exporter.tar.gz
  - echo ">>> Extracting Node Exporter"
  - sudo tar xvfz /run/install/node_exporter.tar.gz -C /run/install/node_exporter --strip-components=1
  - echo ">>> Moving Node Exporter"
  - sudo mv /run/install/node_exporter/node_exporter /usr/local/bin/
  - echo ">>> Starting Node Exporter Service"
  - sudo systemctl daemon-reload
  - sudo systemctl start node_exporter
  - sudo systemctl enable node_exporter
  - echo ">>> Configuring Firewall"
  - sudo firewall-offline-cmd --add-port=9100/tcp 
  - sudo systemctl restart firewalld

final_message: "**** The system is finally up, after $UPTIME seconds ****"
